version: '3.9'
name: whaticket-postgres
services:
  db:
    image: postgres:16.2
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: whaticket
      POSTGRES_USER: user
      POSTGRES_PASSWORD: root
volumes:
  pgdata:
